name: Build and deploy
on: push
jobs:
  build:
    name: Setup and build
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v1
        with:
          node-version: 16.19.0
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build static site
        run: yarn docs:build
      - name: Upload completed build
        uses: actions/upload-artifact@v3
        with:
          name: static-build-result
          path: docs/.vitepress/dist

  deploy:
    name: Deploy to hostinger
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Vitepress build
        uses: actions/download-artifact@v3
        with:
          name: static-build-result
          path: site
      - name: Setup FTP client
        run: sudo apt-get install -y lftp
      - name: Deploy to Hostinger
        env:
          FTP_ADDRESS: ${{ secrets.FTP_ADDRESS }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: lftp -u "${FTP_USERNAME}","${FTP_PASSWORD}" "${FTP_ADDRESS}" -e "set ssl:verify-certificate false ; mirror -R --parallel site . ; quit"
